### ISSUE TITLE
day2 振り返り

### ISSUE THREAD

**Issue by yamato3310** [voyagegroup/hakaru201911-team-b#11]

**Comment by yamato3310** [comment]
# 進め方でうまくいったもの
- コネクションプールの存在を知ることができた
# うまくいかなかったこと
- 悩みすぎていて時間の管理がうまくできなかった
# どうすればうまくいきそうか
- タイマーをつけて強制的に議論を止めるようにする
- 仮説を煮詰まるまで実行に移すことができていなかったので、仮説がある程度整った段階で一度実行に移すようにする

**Comment by pei0804** [comment]
改善前と改善後のエビデンスとかをPRとかissueにいい感じに貼っておきたいな。

**Comment by pei0804** [comment]
改善前と改善後のエビデンスをPRとかissueにいい感じに貼っておきたいな。

**Comment by pei0804** [comment]
ここに、2回目のイテレートについて書こうか。

**Comment by YamagishiRyu** [comment]
## 進め方でうまくいったもの
- 役割分担よくなってきた
- サイクルの回し方がわかってきた
## うまくいかなかったこと
- 時間管理
- まわりのチームのアイディアを盗み見る

## どうすればうまくいきそうか
- 悩む前に行動
