### ISSUE TITLE
SetMaxConnsが効いてるか

### ISSUE THREAD

**Issue by YamagishiRyu** [voyagegroup/hakaru201911-team-b#13]
# アプローチ
#8の続き
#8の最後の実験で接続数は80に制限したが、Too many connectionsが残っている。
これが本当に効いているのかを見たい
setMaxConnsを10にしてみる

## 想定インパクト

SCENARIO１で全て200が返ってくるはず
優先度大
Too manyはなくなるはず
わんちゃんタイムアウトでる？

## モニタリング項目

- EC2 の5XXの数
- ELB の5XXの数
- hakeruのログ

## 結果/考察

**Comment by pei0804** [comment]
なんで、max値を減らしたいのかを、もうちょい説明できるとよさそうやね。

**Comment by YamagishiRyu** [comment]
![image](https://user-images.githubusercontent.com/28495614/68080465-4d03cc00-fe3f-11e9-809e-8e0229463daf.png)
