### ISSUE TITLE
シナリオ２でToo many open filesが出る

### ISSUE THREAD

**Issue by ramenjuniti** [voyagegroup/hakaru201911-team-b#17]
ログ画面
![image](https://user-images.githubusercontent.com/32011829/68080707-21cfab80-fe44-11e9-9f02-652fe78f3fca.png)

**Comment by ramenjuniti** [comment]
https://sunrise201911-team-b-kakeru-report.s3-ap-northeast-1.amazonaws.com/hakaru-365680141.ap-northeast-1.elb.amazonaws.com%3A80/20191103-1405/report.html

**Comment by ramenjuniti** [comment]
![image](https://user-images.githubusercontent.com/32011829/68080720-66f3dd80-fe44-11e9-9c7a-b0312df50df5.png)

**Comment by YamagishiRyu** [comment]
![image](https://user-images.githubusercontent.com/28495614/68080727-8e4aaa80-fe44-11e9-8019-8c5867c1d1cc.png)

**Comment by YamagishiRyu** [comment]
ELB 5XX 92419

**Comment by ramenjuniti** [comment]
エラー一部
`Nov  3 14:11:00 ip-10-1-13-230 hakaru: 2019/11/03 05:11:00 http: Accept error: accept tcp [::]:8081: accept4: too many open files; retrying in 1s`

**Comment by pei0804** [comment]
https://github.com/voyagegroup/hakaru201911-team-b/issues/17#issuecomment-549106480
ELBのせいではないということがわかったとか書くとよき。

**Comment by YamagishiRyu** [comment]
![image](https://user-images.githubusercontent.com/28495614/68080805-26955f00-fe46-11e9-847f-ee5b30afc8f4.png)

CPUは100%近くでmemoryがだいぶ消費されている

**Comment by YamagishiRyu** [comment]
![image](https://user-images.githubusercontent.com/28495614/68080832-796f1680-fe46-11e9-8651-ae20ec4dc7da.png)
file open の上限
なんかソフトとハードの二つある

**Comment by YamagishiRyu** [comment]
https://pikesaku.wiki.fc2.com/wiki/ulimitについて

> ソフトが適用される制限値。
> ハードはユーザーが変更可能な上限値。

**Comment by yamato3310** [comment]
## アプローチ
サーバーのファイルを開ける上限が1024だったため、デフォルトの上限の4096に変更をする
## 想定インパクト
` too many open files`が減るだろう
## モニタリング項目
hakaruのログ
## 結果/考察

**Comment by YamagishiRyu** [comment]
https://sunrise201911-team-b-kakeru-report.s3-ap-northeast-1.amazonaws.com/hakaru-365680141.ap-northeast-1.elb.amazonaws.com%3A80/20191103-1438/report.html

![image](https://user-images.githubusercontent.com/28495614/68080925-c3f19280-fe48-11e9-8afb-8e2ee38ff0e5.png)

**Comment by YamagishiRyu** [comment]
![image](https://user-images.githubusercontent.com/28495614/68081026-7f66f680-fe4a-11e9-8669-53c7e07416e3.png)

**Comment by ramenjuniti** [comment]
https://github.com/voyagegroup/sunrise201911-team-e/issues/11

**Comment by yamato3310** [comment]
## アプローチ
ulimitの上限を上げることによって、さばける量を増やす
http://blog.father.gedow.net/2016/03/28/limits-of-systemd/
## 想定インパクト
`too many open files`をがなくなる
## モニタリング項目
EC2のログ
## 結果/考察

**Comment by YamagishiRyu** [comment]
![image](https://user-images.githubusercontent.com/28495614/68081673-46804f00-fe55-11e9-9836-3c786fed8642.png)

**Comment by pei0804** [comment]
基本なにか確認したらログとか貼ってほしい。何を書いたら出たとかみたい。

**Comment by ramenjuniti** [comment]
https://sunrise201911-team-b-kakeru-report.s3-ap-northeast-1.amazonaws.com/hakaru-365680141.ap-northeast-1.elb.amazonaws.com%3A80/20191103-1616/report.html

**Comment by YamagishiRyu** [comment]
![image](https://user-images.githubusercontent.com/28495614/68081781-b511dc80-fe56-11e9-8da6-c4648293574d.png)

**Comment by ramenjuniti** [comment]
![image](https://user-images.githubusercontent.com/32011829/68081787-c4912580-fe56-11e9-9aaa-74571af5f4c5.png)

**Comment by YamagishiRyu** [comment]
リクエスト数が安定していない、、、８万なんとかぐらいしかない
かけるがいけないんじゃね？→ #21
