### ISSUE TITLE
消えたリクエストの問題がDB周りの処理の遅さが原因かの確認

### ISSUE THREAD

**Issue by yamato3310** [voyagegroup/hakaru201911-team-b#20]
## アプローチ
アプリのDB周りの処理をコメントアウトすることで、レスポンスの時間を早くする
## 想定インパクト
リクエスト数が36万ぐらいに増える
## モニタリング項目
LBのリクエスト数
レポートのリクエストの合計
## 結果/考察

**Comment by ramenjuniti** [comment]
DB処理あり
![image](https://user-images.githubusercontent.com/32011829/68082614-53f00600-fe62-11e9-9320-3764c3c1d5be.png)

DB処理なし
![image](https://user-images.githubusercontent.com/32011829/68082645-9b769200-fe62-11e9-8cd5-0abc3fac8303.png)

**Comment by ramenjuniti** [comment]
kakeruが強くなったのでDB処理を入れて(#28)負荷をかけてみる

**Comment by ramenjuniti** [comment]
強くなったkakeruで負荷をかけた結果
![image](https://user-images.githubusercontent.com/32011829/68095330-cce77000-feeb-11e9-914a-fa49fed34467.png)

リクエスト数が増えてる

**Comment by ramenjuniti** [comment]
強くなったkakeruでDB処理を入れて(#28)負荷をかけてみる

**Comment by YamagishiRyu** [comment]
![image](https://user-images.githubusercontent.com/28495614/68095682-da522980-feee-11e9-8199-041a01b71c19.png)

**Comment by ramenjuniti** [comment]
ログ一部
```
Nov  4 10:32:31 ip-10-1-13-230 hakaru: 2019/11/04 10:32:31 http: panic serving 10.1.3.227:17998: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)
```

**Comment by YamagishiRyu** [comment]
![image](https://user-images.githubusercontent.com/28495614/68095766-914ea500-feef-11e9-801f-e76e2c556e30.png)

redashでmysqlの値を確認したやつ

**Comment by yamato3310** [comment]
## アプローチ
db.Prepareを限界の16382を超えてやろうとしてしまったため、db.Prepareをmainに切り出すようにする
## 想定インパクト
`Can't create more than max_prepared_stmt_count statements `の数が減ると思う
## モニタリング項目
hakaruのログ
## 結果/考察

**Comment by ramenjuniti** [comment]
https://sunrise201911-team-b-kakeru-report.s3-ap-northeast-1.amazonaws.com/hakaru-365680141.ap-northeast-1.elb.amazonaws.com%3A80/20191104-1051/report.html

**Comment by ramenjuniti** [comment]
```
Nov  4 10:57:03 ip-10-1-13-230 kernel: TCP: too many orphaned sockets
```

**Comment by YamagishiRyu** [comment]
![image](https://user-images.githubusercontent.com/28495614/68096130-19ce4500-fef2-11e9-9ca4-2206356eeb16.png)

ELB のログの数とHTTP504の数はともに95602

**Comment by yamato3310** [comment]
## アプローチ
`kernel: TCP: too many orphaned sockets`の原因がtcpソケットの現回数の限界に達してしまったため出ている
対策として、hakaruを2代に増やすことで対策する
## 想定インパクト
今回のエラーがなくなる
## モニタリング項目
ec2のログ
## 結果/考察

**Comment by ramenjuniti** [comment]
ログ
![image](https://user-images.githubusercontent.com/32011829/68098625-04ace280-ff01-11e9-93c5-68d2d147d3df.png)

**Comment by ramenjuniti** [comment]
## アプローチ
SetMaxIdleConnsを増やす（デフォルトは2）

## 想定インパクト
504が減る

## モニタリング項目
EC2のログ

## 結果/考察

**Comment by YamagishiRyu** [comment]
![image](https://user-images.githubusercontent.com/28495614/68099488-3e341c80-ff06-11e9-88aa-547069de6c72.png)

**Comment by ramenjuniti** [comment]
#28 は効果がなかったのでRevert

**Comment by ramenjuniti** [comment]
## アプローチ
コネクションの上限を増やしたいのでインスタンスを2から6に増やす

## 想定インパクト
504がなくなる

## モニタリング項目
EC2のログ

## 結果/考察

**Comment by YamagishiRyu** [comment]
Auto Scaling Groupの設定
![image](https://user-images.githubusercontent.com/28495614/68099891-66247f80-ff08-11e9-827d-fff142ef40da.png)

**Comment by YamagishiRyu** [comment]
![image](https://user-images.githubusercontent.com/28495614/68100149-cbc53b80-ff09-11e9-9e1f-dc7fabf4205d.png)
https://sunrise201911-team-b-kakeru-report.s3-ap-northeast-1.amazonaws.com/hakaru-365680141.ap-northeast-1.elb.amazonaws.com%3A80/20191104-1342/report.html

**Comment by yamato3310** [comment]
## アプローチ
DBの処理が追いついてないため、タイムアウトしているのではないか
対策としてhakaruを6台にして対応する
## 想定インパクト
504がなくなる
## モニタリング項目
ec2のログ
## 結果/考察
上記の画像、すべての504が消えて200になりました

**Comment by ramenjuniti** [comment]
2回目
https://sunrise201911-team-b-kakeru-report.s3-ap-northeast-1.amazonaws.com/hakaru-365680141.ap-northeast-1.elb.amazonaws.com%3A80/20191104-1342/report.html

**Comment by ramenjuniti** [comment]
![image](https://user-images.githubusercontent.com/32011829/68100892-f618f800-ff0d-11e9-9e69-db5d17afd06a.png)

**Comment by yamato3310** [comment]
## アプローチ
db.SetMaxIdleConns(60000)を消したところ、504が出てきてしまった
対策として`db.SetMaxIdleConns(10)`を追加した
10というのは現在のkakeruのDBのmaxコネクション数が10のため
## 想定インパクト
504がなくなる
## モニタリング項目
hakaruのログ
## 結果/考察

**Comment by YamagishiRyu** [comment]
![Uploading image.png…]()
