### ISSUE TITLE
scenario 1で502がでてる

### ISSUE THREAD

**Issue by YamagishiRyu** [voyagegroup/hakaru201911-team-b#5]
![image](https://user-images.githubusercontent.com/28495614/68067312-4d8d5b80-fd88-11e9-91b5-b898eee69080.png)

**Comment by YamagishiRyu** [comment]
![image](https://user-images.githubusercontent.com/28495614/68067366-3602a280-fd89-11e9-8b08-27ff3481e218.png)

1, 2, 3の順で最初にかけた図
これを見る感じ、DBConnectionではない？

**Comment by ramenjuniti** [comment]
200の数はあっていた
アプリケーションの方は大丈夫そう

**Comment by ramenjuniti** [comment]
ロードバランサで503が出てる。数も確認。

**Comment by pei0804** [comment]
> 200の数はあっていた

ここらへん雑でもいいのでスクショほしい。

**Comment by YamagishiRyu** [comment]
実際にELBがスケールしたかどうか自体はわからなそう
データやログからはわからない

## 仮説
１回目が失敗して2回目が成功したのはスケールしたからと考えられる。
だからこれ以降は失敗しないのではないか

**Comment by YamagishiRyu** [comment]
# もしこれ以降ダメでその時のために出てきた対策
・プリウォーミングをしとく
・ELBが自動で増える/減る仕様が知りたい

**Comment by pei0804** [comment]
> ロードバランサで502が出てる。数も確認。

レポートの数と合ってたって話ね。

**Comment by YamagishiRyu** [comment]
もう一回投げたら失敗した
![image](https://user-images.githubusercontent.com/28495614/68067701-96e0a980-fd8e-11e9-961e-8e02d2eb43db.png)
レポートで502が57件起きて、それがアプリケーションのログの数と一致

**Comment by YamagishiRyu** [comment]
ログ見たらエラー出てた
![Uploading image.png…]()

**Comment by YamagishiRyu** [comment]
RDSのログみたらDB接続多くなくない？
![image](https://user-images.githubusercontent.com/28495614/68067756-4158cc80-fd8f-11e9-8a62-c25369fab5b5.png)

**Comment by YamagishiRyu** [comment]
https://github.com/voyagegroup/hakaru201911-team-b/blob/af1670297e81c23569afcef29f7373c30c6fff82/main.go#L28
ここでエラー

**Comment by yamato3310** [comment]
Too many connectionsの対策としてmax_connectionsを増やすことによって解決する方法もあるが、そもそもRDSのコネクション数は問題なさそう

**Comment by ramenjuniti** [comment]
DBの方には問題がないだろうと判断。main.goを調査。

ここでリクエストのたびにDBをOpenしてる
https://github.com/voyagegroup/hakaru201911-team-b/blob/af1670297e81c23569afcef29f7373c30c6fff82/main.go#L20

**Comment by ramenjuniti** [comment]
☝️#6 で変更

**Comment by YamagishiRyu** [comment]
# アプローチ
DBの接続をリクエストのたびにしているようだったからそれをしないようにする

## 想定インパクト

SCENARIO１で全て200が返ってくるはず
優先度大

## モニタリング項目

- EC2 の5XXの数
- ELB の5XXの数

## 結果/考察
回し中....

**Comment by pei0804** [comment]
ログとメトリクスをさっさと見るとよかった。

**Comment by YamagishiRyu** [comment]
変わらなかった
![image](https://user-images.githubusercontent.com/28495614/68068295-7caac980-fd96-11e9-84ef-49f425e382bd.png)

![image](https://user-images.githubusercontent.com/28495614/68068314-b1b71c00-fd96-11e9-9068-09368c546663.png)
エラーを見るとToo many connectionがでてる

**Comment by pei0804** [comment]
かなぴい

**Comment by pei0804** [comment]
ここに、1でやった施策で効いたものを書いて閉じていこう。

**Comment by pei0804** [comment]
issueリンクあるとなおよし

**Comment by yamato3310** [comment]
結局DBのコネクションをアクセスごとに繋いでいるというのと、poolが無制限だったことが`Too many connection`の原因
対策として、DBのコネクション周りをMainの方に退避させるのとpoolに上限を持たさることでこのエラーを消すことができた
