### ISSUE TITLE
day1振り返り

### ISSUE THREAD

**Issue by pei0804** [voyagegroup/hakaru201911-team-b#7]

**Comment by YamagishiRyu** [comment]
## 進め方でうまくいったもの
- モブプロ
- 集中して調べる時間をとったのがよかった
- ちゃんとログをみて根拠をしっかり得ようとしてた
- みんな発言できてた

## うまくいかなかったこと
- モブプロの画面共有者がいろいろやり過ぎてた
- 時間とかを意識
- ログを深く見る前に次の行動にうつってしまった

## どうすればうまくいきそうか
- 役割分担しっかり(ログ見る人とか)
- ログをちゃんと保存&考察する
