### ISSUE TITLE
Too many connectionがでてる

### ISSUE THREAD

**Issue by YamagishiRyu** [voyagegroup/hakaru201911-team-b#8]
# アプローチ
Connectionの最大上限が決まってなくて[参考](https://golang.org/src/database/sql/sql.go?s=37987:38065#L1390)、無限につなごうとするけど、リソース的に限界がきている。
よって上限を決めてしまい、それ以上の処理がきたら待ってもらう

## 想定インパクト

SCENARIO１で全て200が返ってくるはず
優先度大

## モニタリング項目

- EC2 の5XXの数
- ELB の5XXの数
- hakeruのログ

## 結果/考察

**Comment by YamagishiRyu** [comment]
```
		stmt, e := db.Prepare("INSERT INTO eventlog(at, name, value) values(NOW(), ?, ?)")
		if e != nil {
			panic(e.Error())
		}
```
ここのPanicでerrorが出る

**Comment by YamagishiRyu** [comment]
https://qiita.com/methane/items/ccd3fd856b02b06c9452#対策その1-max-idle-を十分大きくする

**Comment by YamagishiRyu** [comment]
Connectionが使い回せてないのは結局想定外の数が来た時点で結局想定以上の接続を試みるはずなので問題ではなさそう

**Comment by ramenjuniti** [comment]
https://system.blog.uuum.jp/entry/go-database-sql-stop-the-world

空きコネクションが無いと、コネクションが取れるまで待つ
https://github.com/golang/go/blob/release-branch.go1.6/src/database/sql/sql.go#L800-L817

**Comment by YamagishiRyu** [comment]
![image](https://user-images.githubusercontent.com/28495614/68079462-45d3c280-fe2d-11e9-9cab-37f6f80e012b.png)

**Comment by YamagishiRyu** [comment]
![image](https://user-images.githubusercontent.com/28495614/68079479-921f0280-fe2d-11e9-9945-222f4ef31d71.png)

**Comment by ramenjuniti** [comment]
https://sunrise201911-team-b-kakeru-report.s3-ap-northeast-1.amazonaws.com/hakaru-365680141.ap-northeast-1.elb.amazonaws.com%3A80/20191103-1124/report.html
